### ISSUE TITLE
README docker-compose

### ISSUE THREAD

**Issue by FabioMD1972** [ViktorSalimonov/pylette#10]
Hi,
I'm not an expert and this is my first time with Celery and docher-compose.

In readme I had to use sudo (on ubuntu) in order to run docker-compose commands.  Moreover instead "docker-compose run" I had to use "sudo docker-compose up".

I don't know if it is a bug in your readme, anyway it works for me as you can read above.

Tks very much for your code.

f.

**Comment by ViktorSalimonov** [comment]
@FabioMD1972 Hi, mate!

I'll check the installation steps and fix it.

Thanks for sharing this issue!

**Comment by ViktorSalimonov** [comment]
Updated :)
