### ISSUE TITLE
Cannot connect to redis://localhost:6379

### ISSUE THREAD

**Issue by getcontrol** [ViktorSalimonov/pylette#14]
Environment : 
macOS = Mojave
Python v= 3.7.5 (ran in venv)
Redis server v=5.0.7 
Celery v=4.4.0 
Docker = 18.09.1

Followed all of the instructions as per Medium article. 

On running Docker compose up :

worker_1  ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address.

**Comment by partrita** [comment]
same here

**Comment by ViktorSalimonov** [comment]
Hey, folks!
The celery broker configuration in the `docker-compose.yml` and `config.yml` was updated.
Thanks a lot for the issue!
